vsrad/radeon-asm-tools

VSRAD.Syntax/Constants.cs, VSRAD.Syntax/Guide/IndentGuide.cs, VSRAD.Syntax/Guide/IndentGuideFactory.cs, VSRAD.Syntax/Options/Options.cs, VSRAD.Syntax/Parser/BaseParser.cs, VSRAD.Syntax/Parser/Blocks/BaseBlock.cs, VSRAD.Syntax/Parser/Blocks/FunctionBlock.cs, VSRAD.Syntax/Parser/Blocks/IBaseBlock.cs, VSRAD.Syntax/Parser/ParserManger.cs, VSRAD.Syntax/Parser/ParserProvider.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
Indent guide lines highlighting and options.
=> Indent guide

VSRAD.Package/DebugVisualizer/NumberInput.xaml, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/ToolWindows/ControlStyle.xaml, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/VSRAD.Package.csproj
* `Debug visualizer` header color theme is now supported
* `Options window` color theme is now supported
=> WIP: Basic color theme support

VSRAD.Package/ProjectSystem/Macros/MacroEditorWindow.xaml, VSRAD.Package/ProjectSystem/Profiles/ProfileNameWindow.xaml, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml, VSRAD.Package/ToolWindows/ControlStyle.xaml
* Profile window is now support
* New profile window is now support
* Macro editor window is now support
* Some fixes in options window
=> WIP: color theme for some windows

VSRAD.DebugServer/Handlers/ExecuteHandler.cs, VSRAD.DebugServer/IPC/Responses.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml.cs, VSRAD.Package/Server/BreakState.cs, VSRAD.Package/Server/DebugSession.cs
* **Total time**:
Includes deploy time, execution time, fetch result time.
* **Execution time**:
Includes only application execution time.
=> Timing info (total and app execution time)

VSRAD.DeborgarTests/VSRAD.DeborgarTests.csproj, VSRAD.Package/VSRAD.Package.tt, VSRAD.PackageTests/VSRAD.PackageTests.csproj, VSRAD.Syntax/VSRAD.Syntax.csproj
1)DOS and Windows endings
2)Missing LangVersion
=> [fix] Project build in Release

VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighlighterTagger.cs, VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighlighterTaggerProvider.cs, VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighliterTagger.cs, VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighliterTaggerProvider.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
Error highlighting on start debug with standard syntax error tag.
=> Error highlight

VSRAD.BuildTools/Errors/LineMapper.cs, VSRAD.BuildTools/Errors/Parser.cs, VSRAD.BuildToolsTests/Errors/LineMapperTests.cs
Extract filenames as well as line numbers from line markers
=> New preprocessed parser logic

VSRAD.Package/Commands/PreprocessCommand.cs, VSRAD.Package/Constants.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.Package/VSRAD.Package.tt, VSRAD.PackageTests/BuildTools/BuildToolsServerTest.cs
=> Preprocess

VSRAD.Syntax/Collapse/OutliningTagger.cs, VSRAD.Syntax/FunctionList/Commands/FunctionListCommand.cs, VSRAD.Syntax/FunctionList/FunctionList.cs, VSRAD.Syntax/FunctionList/FunctionListControl.xaml, VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/Guide/IndentGuide.cs, VSRAD.Syntax/Guide/IndentGuideFactory.cs, VSRAD.Syntax/Helpers/Error.cs, VSRAD.Syntax/Options/Options.cs, VSRAD.Syntax/Parser/BaseParser.cs, VSRAD.Syntax/Parser/ParserManger.cs, VSRAD.Syntax/Parser/ParserProvider.cs, VSRAD.Syntax/SyntaxHighlighter/Classifier.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
* Code cleanup
* Changed color theme for function list
* Immediate loading current function list on opening Function List window event
=> Syntax plugin improvements

VSRAD.Package/Commands/BaseRemoteCommand.cs, VSRAD.Package/Commands/DisassemblyCommand.cs, VSRAD.Package/Commands/PreprocessCommand.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs
Resolves #26 
Added `Line Marker` option for preprocessor
=> Preprocessor Line Marker

VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml, VSRAD.Package/ProjectSystem/Profiles/PropertyPageEditorWrapper.cs
* changed tabs order
* grouped  `Output Path`, `Output Mode`, `Output Offset` together in the Debugger tab
* aligned option text and it's label
* keep identical vertical spacing between lines
=> #23 GUI profile options improvements

VSRAD.Package/BuildTools/BuildErrorProcessor.cs, VSRAD.Package/BuildTools/Errors/LineMapper.cs, VSRAD.PackageTests/BuildTools/Errors/LineMapperTests.cs
* Line mapping fixes
* Errors without line number handling
=> Error handling

VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/Options/ProjectOptions.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsReflector.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileTransferManager.cs, VSRAD.Package/ProjectSystem/Profiles/PropertyPageEditorWrapper.cs, VSRAD.PackageTests/ProjectSystem/Profiles/ProfileTransferManagerTests.cs
Refactored old code that related to profile name storing, displaying and editing in profile options interface
=> Profile options refactor

VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/Helpers/BaseBlockExtension.cs, VSRAD.Syntax/Helpers/TextSnapshotExtension.cs, VSRAD.Syntax/Helpers/TextViewExtension.cs, VSRAD.Syntax/Helpers/TextViewParserExtension.cs, VSRAD.Syntax/Parser/BaseParser.cs, VSRAD.Syntax/Parser/Blocks/FunctionBlock.cs, VSRAD.Syntax/Parser/ParserManger.cs, VSRAD.Syntax/Parser/Tokens/FunctionToken.cs, VSRAD.Syntax/Parser/Tokens/IDescriptionToken.cs, VSRAD.Syntax/Parser/Tokens/VariableToken.cs, VSRAD.Syntax/Peek/DefinitionService/DefinitionService.cs, VSRAD.Syntax/QuickInfo/QuickInfoSource.cs, VSRAD.Syntax/QuickInfo/QuickInfoSourceProvider.cs, VSRAD.Syntax/SyntaxHighlighter/Classifier.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
Shows quick info on mouse over.
- shows description (like comments)
- shows declaration (variable or function)
=> Quick info implementation (resolve #46)

VSRAD.Package/DebugVisualizer/ColumnStyling.cs, VSRAD.Package/DebugVisualizer/ContentAlignment.cs, VSRAD.Package/DebugVisualizer/CustomTableGraphics.cs, VSRAD.Package/DebugVisualizer/FontType.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/Options/ProjectOptions.cs, VSRAD.Package/Options/VisualizerAppearance.cs, VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/ToolWindows/ControlStyle.xaml, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/Utils/SeparatorColorConverter.cs, VSRAD.Package/VSRAD.Package.csproj
Resolves #54 
Adds new expander to a Options window that contains
* Name header alignment
* First column alignment
* Header alignment (except Name)
* Data alignment
* Name font: normal or bold
* First column font: normal or bold
* Header font (except Name): normal or bold
* Group lanes by separator width
* Group lanes by separator color
* Hidden columns separator width
* Hidden columns separator color
settings.
=> Gui features

VSRAD.Package/DebugVisualizer/CustomTableGraphics.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/Options/VisualizerAppearance.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/Server/FileSynchronizationManager.cs, VSRAD.Package/ToolWindows/ControlStyle.xaml, VSRAD.Package/ToolWindows/OptionsControl.xaml
* Fixed some option names and alignments
* Moved autosave option from profiles to general options window
* Added checkboxes for some options for convenience
=> Gui improvements

VSRAD.Package/DebugVisualizer/CellStyling.cs, VSRAD.Package/DebugVisualizer/ColumnSelector.cs, VSRAD.Package/DebugVisualizer/ColumnStyling.cs, VSRAD.Package/DebugVisualizer/ColumnStylingOptions.cs, VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/ContextMenus/SubgroupContextMenu.cs, VSRAD.Package/DebugVisualizer/DataHighlightColor.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/DebugVisualizer/VisualizerTable.cs
=> Group size handling

VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs
The Line Number column width was set incorrectly at the first start of the Function List, due to which the data was displayed incorrectly. 
In order to reproduce the bug: **_make sure FL was closed -> open VS -> open some Radeon Asm file -> open FL view_**
This bug can be seen in the following picture:
=> Fixed incorrect line number column width after first FL launch

VSRAD.Package/DebugVisualizer/GroupIndexSelector.cs, VSRAD.Package/DebugVisualizer/VisualizerContext.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Macros/MacroListEditor.xaml.cs, VSRAD.PackageTests/DebugVisualizer/GroupIndexSelectorTests.cs
Added `RadGroupSize` macro that represents group size from visualizer table interface
=> Rad group size

VSRAD.Package/Options/ProjectOptions.cs
Handle situation when `.conf.json` is readonly
=> handle readonly config file

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/DebugVisualizer/MouseMove/ReorderOperation.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs
Addresses #130 
Addresses #133 
* Fixed reordering issue - after adding a new watch it was impossible to change its position
* Removing empty brackets from watch name
=> Visualizer fixes

VSRAD.Package/Options/ProjectOptions.cs
=> Fix crash when configuration file is empty

VSRAD.Syntax/FunctionList/FunctionList.cs, VSRAD.Syntax/FunctionList/FunctionListControl.xaml, VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/FunctionList/FunctionListItem.cs, VSRAD.Syntax/FunctionList/Helper.cs
Added filter by type of tokens in the FL. 
Filter has three states:
* FL - functions and labels are included in the list
* F - only functions are included in the list
* L - only labels are included in the list
These states change cyclically when you press the button.
=> Filter by type button in the function list

VSRAD.Package/Commands/ActionsMenuCommand.cs, VSRAD.Package/Server/CommunicationChannel.cs
Sending multiple commands in parallel could lead to unexpected behavior
=> Fix race condition when sending multiple commands in parallel

VSRAD.Package/Commands/ProfileDropdownCommand.cs, VSRAD.Package/Constants.cs, VSRAD.Package/Options/Actions.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/Options/ProjectOptions.cs, VSRAD.Package/ProjectSystem/ActionLauncher.cs, VSRAD.Package/ProjectSystem/Macros/DirtyProfileMacroEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditContext.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/BuiltinActionFileEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/BuiltinActionFileEditor.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/FileSynchronizationManager.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/ToolWindows/OptionsControl.xaml.cs, VSRAD.Package/Utils/MruCollection.cs, VSRAD.Package/Utils/WpfConverters.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.Package/VSRAD.Package.tt, VSRAD.PackageTests/ProjectSystem/Macros/MacroEvaluatorTests.cs, VSRAD.PackageTests/Server/ActionMacroEvaluationTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs, VSRAD.PackageTests/Server/FileSynchronizationManagerTests.cs
This PR:
* Resolves #173
* Adds a toolbar dropdown for changing remote machine address without going to the profile editor
=> Localhost switch in profile settings

VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/DebugVisualizer/Wavemap/WavemapOffsetInput.xaml, VSRAD.Package/DebugVisualizer/Wavemap/WavemapOffsetInput.xaml.cs
Small fix - made the top and bottom margins dynamic, so they depend of content height
=> Wavemap offset selector fix

VSRAD.Syntax/Core/DocumentFactory.cs, VSRAD.Syntax/Core/Lexer/Asm2Lexer.cs, VSRAD.Syntax/Core/Parser/AbstractCodeParser.cs, VSRAD.Syntax/Core/Parser/Asm1Parser.cs, VSRAD.Syntax/Core/Parser/Asm2Parser.cs, VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/FunctionList/FunctionListProvider.cs, VSRAD.Syntax/FunctionList/FunctionListWindow.cs, VSRAD.SyntaxParser/RadAsm2.g4
=> Syntax fixes

VSRAD.Package/ProjectSystem/ProjectSourceManager.cs
Fixed a error with saving opened files if some of them are presented in Visual Studio as tabs, but the files have already been removed from the file system.
=> Fix opened files error

VSRAD.Package/VSRAD.Package.tt
`Alt+D`: Disassemble, `Alt+W`: Profile
The keybindings can be changed in _Tools_ -> _Options_ -> _Keyboard_.
=> Add default keybindings for disassemble and profile actions

VSRAD.Syntax/IntelliSense/Completion/Providers/FunctionCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/InstructionCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/RadCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/ScopedCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/TokenTypeExtension.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
This PR changes token icons in the intellisense popup.
=> New intellisense icons

VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml
Moved Most Recently Used toggle button to the left side of control.
=> MRU Interface Redesign

VSRAD.Package/ProjectSystem/ProjectSourceManager.cs
Fixed a error with saving opened files if some of them are presented in Visual Studio as tabs, but the files have already been removed from the file system.
=> Fix error on attempt to save deleted files

VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/FunctionList/FunctionListProvider.cs, VSRAD.Syntax/FunctionList/Helper.cs
Same as #221, but into `dev-stable`
=> Function List sorting and filtering

VSRAD.Package/Options/DebuggerOptions.cs
=> Misplaced annotations fix

VSRAD.Syntax/Core/Tokens/TokenType.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/FunctionCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/InstructionCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/RadCompletionProvider.cs, VSRAD.Syntax/IntelliSense/Completion/Providers/ScopedCompletionProvider.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs, VSRAD.Syntax/IntelliSense/TokenTypeExtension.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
This PR changes token icons in the intellisense popup (same as #216 PR).
- Updated icons for tokens: `function, parameter, local variable, global variable`
- Added icons in the quick-info popup
=> Intellisense icons

VSRAD.Package/DebugVisualizer/FontAndColorProvider.cs, VSRAD.Package/DebugVisualizer/GroupIndexSelector.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerContext.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerContext.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/Wavemap/WavemapImage.cs, VSRAD.Package/ProjectSystem/ActionLauncher.cs, VSRAD.Package/ProjectSystem/SolutionManager.cs, VSRAD.Package/ProjectSystem/ToolWindowIntegration.cs, VSRAD.Package/Server/CommunicationChannel.cs, VSRAD.Package/ToolWindows/BaseToolWindow.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml.cs, VSRAD.Package/ToolWindows/SliceVisualizerWindow.cs, VSRAD.Package/ToolWindows/VisualizerWindow.cs, VSRAD.Package/VSPackage.cs, VSRAD.PackageTests/MockCommunicationChannel.cs
This PR is readding @timlathy's logic to prevent memory leaks on solution close.
=> Fix memory leaks [stable]

VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs, VSRAD.PackageTests/ProjectSystem/Profiles/ObsoleteFormatProfileImportTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs
Resolves #293 
Fixed some failing unit tests.
=> Unit tests fix

VSRAD.Syntax/Core/DocumentFactory.cs, VSRAD.Syntax/Core/IDocumentFactory.cs, VSRAD.Syntax/FunctionList/FunctionListProvider.cs
Resolves #313 
Added additional things so #301 would work for `master`.
=> Fix: Function List proper Open in Editor handling [master]

VSRAD.Package/DebugVisualizer/ContextMenus/TypeContextMenu.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs
Resolves #304 
___
This PR adds `Add to watches as array` item in the context menu for each watch, then clicking on `bb[5]` -> `Add to watches as array` from 0 to 1 will insert `bb[5][0]` and `bb[5][1]`
=> Visualizer nested list support

VSRAD.DebugServer/IPC/Commands.cs, VSRAD.DebugServer/Logging/ClientLogger.cs, VSRAD.DebugServer/Server.cs, VSRAD.DebugServer/VSRAD.DebugServer.csproj, VSRAD.Package/Constants.cs, VSRAD.Package/Server/CommunicationChannel.cs
Resolves [#324 ](url)
Added version handshake checking
=> Added version checking in handshake during connection to debug server

VSRAD.DebugServer/Logging/ClientLogger.cs, VSRAD.DebugServer/Logging/GlobalLogger.cs, VSRAD.DebugServer/VSRAD.DebugServer.csproj
Added file logging with rotation
=> Added logging to file

VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs
=> Fixed crash function list crush

VSRAD.Package/DebugVisualizer/ContextMenus/TypeContextMenu.cs, VSRAD.Package/DebugVisualizer/VariableType.cs, VSRAD.PackageTests/Server/BreakStateTests.cs
Fixes error in #346 when all types were deserialized from json as `Hex`
Also rearranged type menu
=> Packed types Fixes

VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/Options/DebuggerOptions.cs
This PR sets minimum value for Counter property to 1.
=> Set new Counter minimum

VSRAD.Package/ProjectSystem/ErrorListManager.cs, VSRAD.Package/ProjectSystem/OutputWindow.cs
* Automatically focus on Error List when command execution terminates with errors
* Automatically select the "RAD Output" tab in Output when printing command output there
=> Command handling improvements

VSRAD.Package/ProjectSystem/ActionController.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Utils/VsStatusBarWriter.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs
* Show action progress in VS status bar
* Clarify `Copy File/Directory` step error messages
* Skip Local-to-Local copies when the source and target paths are the same
=> Improve action progress and error reporting
