vsrad/radeon-asm-tools

VSRAD.DebugServer/Handlers/FetchResultRangeHandler.cs, VSRAD.DebugServer/IPC/Commands.cs, VSRAD.DebugServerTests/Handlers/FetchResultRangeHandlerTest.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/Server/BreakState.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.PackageTests/Server/BreakStateTests.cs
* Added custom offset property (`Profile edit->Debugger`)
* When output mode is `binary` indicates amount of bytes to skip
* When output mode is `text` indicates amount of lines to skip
* Fixed text offset bug
=> Custom offset

VSRAD.DebugServer/Dispatcher.cs, VSRAD.DebugServer/Handlers/ListEnvironmentVariablesHandler.cs, VSRAD.DebugServer/IPC/Commands.cs, VSRAD.DebugServer/IPC/IPCSerialization.cs, VSRAD.DebugServer/IPC/Responses.cs, VSRAD.DebugServerTests/Handlers/ExecuteHandlerTest.cs, VSRAD.DebugServerTests/Handlers/ListEnvironmentVariablesHandlerTest.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditManager.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditorWindow.xaml, VSRAD.Package/ProjectSystem/Macros/MacroEditorWindow.xaml.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/PropertyPageEditorWrapper.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml.cs, VSRAD.Package/Utils/RegexUtils.cs, VSRAD.Package/VSRAD.Package.csproj
This PR adds support for local and remote environment macros. In addition to the existing `$(...)` syntax, the following forms are now recognized:
* `$ENV(...)`: substituted with the value of a local environment variable
* `$ENVR(...)`: substituted with the value of an environment variable on the remote machine
Both local and remote environment variables can be previewed in Macro Editor.
=> Environment macros

VSRAD.BuildTools/IPCBuildResult.cs, VSRAD.BuildTools/RemoteBuildStderrParser.cs, VSRAD.BuildTools/RemoteBuildTask.cs, VSRAD.BuildToolsTests/RemoteBuildStderrParserTests.cs, VSRAD.Package/BuildTools/BuildToolsServer.cs, VSRAD.Package/Commands/DisassemblyCommand.cs, VSRAD.Package/Commands/EvaluateSelectedCommand.cs, VSRAD.Package/Commands/ProfileCommand.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/Server/RemoteCommandExecutor.cs, VSRAD.PackageTests/BuildTools/BuildToolsServerTest.cs, VSRAD.PackageTests/Server/RemoteCommandExecutorTests.cs
When using a separate preprocessing step, compiler error messages may refer to incorrect line numbers in the original source file.
This PR adds a new option, **Preprocessed Source** (**Build**). When specified, error locations are updated based on the [`#` linemarkers](https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html) in the preprocessed source.
=> Build: use preprocessed source to map lines in error messages

VSRAD.BuildTools/Errors/LineMapper.cs, VSRAD.BuildTools/Errors/Message.cs, VSRAD.BuildTools/Errors/Parser.cs, VSRAD.BuildTools/RemoteBuildStderrParser.cs, VSRAD.BuildTools/RemoteBuildTask.cs, VSRAD.BuildTools/VSRAD.BuildTools.csproj, VSRAD.BuildToolsTests/Errors/LineMapperTests.cs, VSRAD.BuildToolsTests/Errors/ParserTests.cs, VSRAD.BuildToolsTests/RemoteBuildStderrParserTests.cs, VSRAD.BuildToolsTests/VSRAD.BuildToolsTests.csproj
Automatically detect Clang/script error message formats and parse them accordingly.
=> Build: alternative error format

VSRAD.Package/BuildTools/BuildToolsServer.cs, VSRAD.Package/Commands/DisassemblyCommand.cs, VSRAD.Package/Commands/PreprocessCommand.cs
* Add a way to programmatically override build steps for the next project build (e.g. so it only runs *preprocess* or *disassemble*)
* Implement DA and PP commands as wrappers over project build (resolves #27)
=> Run DA and PP as a part of project build

VSRAD.DebugServer/IPC/IPCSerialization.cs, VSRAD.DebugServerTests/Handlers/ExecuteHandlerTest.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditManager.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/Server/CommunicationChannel.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml.cs, VSRAD.PackageTests/ProjectSystem/MacroEvaluatorTests.cs
Upon connecting to the server, the extension requests a list of environment variables defined on the remote host. This information is stored until the connection is closed and used by `MacroEvaluator`.
Resolves #24
=> Perform $ENVR macro substitution on VS side

VSRAD.Package/DebugVisualizer/ColumnSelector.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.PackageTests/DebugVisualizer/ColumnSelectorTests.cs
New ranges selected from context menu multiplies by current selector, unless current column set is a subset of a new one - in that case new selector uses "as is".
=> Column selector rewrite

VSRAD.Package/BuildTools/BuildToolsServer.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/ProjectSystem/BreakpointIntegration.cs, VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/ProjectSystem/ProjectLifecycle.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/VSRAD.Package.csproj
Unfortunately, Visual Studio does not provide an API to observe breakpoints in design mode:
* ["After consulting with the debugger team, there is no public API for this."](https://social.msdn.microsoft.com/Forums/en-US/fe2e7263-c0a2-40d1-9349-5c64a3e5b188/how-do-i-detect-a-breakpoint-being-deleted-in-visual-studio?forum=vsx)
* ["After some discussion with the Ms VS team, there is no service to get event from the breakpoint window."](https://social.msdn.microsoft.com/Forums/en-US/ada85864-a5ef-4191-8e82-dd1f3fa54446/how-to-get-notified-when-user-remove-a-breakpoint-from-the-breakpoint-window?forum=vsx)
The approach taken in this PR is not pretty, but it works: we poll the DTE breakpoint list every 250 milliseconds (this delay can be tweaked later) to detect state changes. No polling is …
=> Add an option to disable existing breakpoints when a new one is added

VSRAD.Deborgar/BreakpointManager.cs, VSRAD.Deborgar/EngineCallback.cs, VSRAD.Deborgar/ExecutionController.cs, VSRAD.Deborgar/IEngineIntegration.cs, VSRAD.Deborgar/Program.cs, VSRAD.Deborgar/SourceFileLineContext.cs, VSRAD.DeborgarTests/ProgramTests.cs, VSRAD.Package/Commands/EvaluateSelectedCommand.cs, VSRAD.Package/DebugVisualizer/ColumnStyling.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/ProjectSystem/BreakpointIntegration.cs, VSRAD.Package/ProjectSystem/DebuggerIntegration.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/ToolWindows/OptionsControl.xaml.cs, VSRAD.Package/Utils/ContinueMode.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.PackageTests/BuildTools/BuildToolsServerTest.cs, VSRAD.PackageTests/ProjectSystem/MacroEvaluatorTests.cs, VSRAD.PackageTests/Server/DebugSessionTests.cs, VSRAD.PackageTests/Server/FileSynchronizationManagerTests.cs, VSRAD.PackageTests/TestHelper.cs
Implements #62
*Disable other breakpoints when adding a new one* and *Continue mode* options are now merged into a single *Break mode* dropdown. It also includes a new mode where `$(RadBreakLine)` expands to a comma-separated list of all breakpoints in the current file.
The issue mentions drawing a stop arrow on all breakpoints when the mode is set to multiple, but I couldn't find an easy way to do that and seeing how it's marked as low priority I think it can be postponed.
=> Multiple breakpoints

VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/ProjectSystem/DebuggerIntegration.cs, VSRAD.Package/Server/BreakState.cs, VSRAD.Package/Server/BreakStateData.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.Package/Server/RemoteCommandExecutor.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs, VSRAD.PackageTests/Server/BreakStateTests.cs, VSRAD.PackageTests/Server/DebugSessionTests.cs, VSRAD.PackageTests/Server/RemoteCommandExecutorTests.cs
* Display watch data regardless of the debug script exit code
* Gray out watch data if execution fails (could not launch, timed out, stale data, etc.)
* Include execution status (exit code, timed out, could not launch) in RAD Output messages
To accommodate the new slice visualizer feature:
* Store break data in a contiguous array, use a bit vector to track which parts are fetched (one bit per 64 items, the smallest group size)
* Access watches via a view into the original data array instead of allocating an array per watch
=> Rewrite break state

VSRAD.Syntax/FunctionList/FunctionList.cs, VSRAD.Syntax/FunctionList/FunctionListEventFactory.cs
The problem was that the function was not highlighted in the Function List if the caret was on the signature line. 
The function was highlighted only if the cursor was in the scope of the function as in the following pictures:
This PR solves this problem, now the function is correctly highlighted in the FL. Also now the cursor position is used to highlight the function, not the line.
=> Function signature did not participate in function detection

VSRAD.DebugServer/IPC/Commands.cs, VSRAD.DebugServer/IPC/Responses.cs, VSRAD.Package/BuildTools/BuildToolsServer.cs, VSRAD.Package/Commands/ActionsMenuCommand.cs, VSRAD.Package/Commands/EvaluateSelectedCommand.cs, VSRAD.Package/Options/Actions.cs, VSRAD.Package/Options/BuiltinActionFile.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/ActionLogger.cs, VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs, VSRAD.Package/ProjectSystem/Macros/DirtyProfileMacroEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEditContext.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Macros/MacroListEditor.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml.cs, VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.Package/Server/FileSynchronizationManager.cs, VSRAD.PackageTests/ProjectSystem/ActionLoggerTests.cs, VSRAD.PackageTests/ProjectSystem/Macros/MacroEditContextTests.cs, VSRAD.PackageTests/ProjectSystem/Macros/MacroEvaluatorTests.cs, VSRAD.PackageTests/Server/ActionMacroEvaluationTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs, VSRAD.PackageTests/Server/FileSynchronizationManagerTests.cs, VSRAD.PackageTests/TestHelper.cs
Profile editor:
* Evaluate macros in step descriptions (159681f)
* Prevent freezes when step configuration is invalid (aae92d1, 4c75bc3)
Macro/action evaluation:
* Show descriptive error messages for missing parameters in step configuration (0f72b03)
* If working directory is not specified for `Execute` step, set it to *General* -> *Local Working Directory* / *Remote Working Directory* depending on step environment (0c31bda)
* Add `$(RadActiveSourceDir)` and `$(RadActiveSourceFullPath)` macros, change `$(RadActiveSourceFile)` to evaluate to file name only -- previously, it evaluated to a project-relative file path, which could cause "File does not belong to the current project" errors (43190a9)
Debug server:
* Deploy project files before running actions (d69bc76)
* Restore backward …
=> Further profile improvements

VSRAD.Syntax/Collapse/OutliningTagger.cs, VSRAD.Syntax/FunctionList/FunctionList.cs, VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/Helpers/ParserResultExtension.cs, VSRAD.Syntax/IntelliSense/Completion/CompletionSource.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs, VSRAD.Syntax/IntelliSense/Navigation/NavigationTokenService.cs, VSRAD.Syntax/Options/InstructionListManager.cs, VSRAD.Syntax/Parser/DocumentAnalysis.cs, VSRAD.Syntax/Parser/RadAsm/AsmParser.cs, VSRAD.Syntax/Parser/RadAsm2/Asm2Parser.cs, VSRAD.Syntax/SyntaxHighlighter/Classifier.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
Parser:
* Fixed a critical error if the shader source code was written incorrectly (function parameters have the same names), code highlighting and FL did not work (https://github.com/vsrad/radeon-asm-tools/commit/aab349391c3dc04c3aeecbc071600470c305894e)
* Fixed error when opening an already open source file. This can be reproduced when opening a file using RadeonAsmDebugger (https://github.com/vsrad/radeon-asm-tools/pull/112/commits/f02e2316341a5337ef24926a8da37e2bc7c83741)
Function list:
* Fixed filtering of the FL when changing the code window (if the filter was set). The filter was not applied before (https://github.com/vsrad/radeon-asm-tools/commit/971e212f61e860b7c3575dd3fa1ccb1b0b90a6be)
* Fixed `Line Number` column width with large numbers …
=> Syntax bug fixes

VSRAD.Syntax/IntelliSense/Completion/CompletionSource.cs, VSRAD.Syntax/IntelliSense/Completion/CompletionSourceProvider.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs, VSRAD.Syntax/IntelliSense/Navigation/NavigationList/DefinitionToken.cs, VSRAD.Syntax/IntelliSense/QuickInfo/QuickInfoSource.cs, VSRAD.Syntax/IntelliSense/QuickInfo/QuickInfoSourceProvider.cs, VSRAD.Syntax/Parser/Tokens/TokenType.cs, VSRAD.Syntax/SyntaxHighlighter/Classifier.cs
Text elements now support navigation in the QuickInfo tooltip. 
It's works for
* instructions
* variables
* function parameters
* functions (the function signature is shown and navigation is available for the function name and parameters)
> <img width="495" alt="pr" src="https://user-images.githubusercontent.com/40007198/88281864-1897af00-ccf1-11ea-9c1e-50791d8d58de.PNG">
=> Navigable quickInfo text elements

VSRAD.Package/DebugVisualizer/ColumnStyling.cs, VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/RowStyling.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs
* Fixed unevaluated watches painting
* Gray out all watches before debug session start
* Properly gray out watches if debug session was unsuccessfull
=> Unevaluated watches handling fixes

VSRAD.Package/ProjectSystem/ErrorListManager.cs, VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighlighterTagger.cs, VSRAD.Syntax/SyntaxHighlighter/ErrorHighlighter/ErrorHighlighterTaggerProvider.cs
Error highlighting in source files used to be applied after project build. Since #110, we don't use MSBuild anymore, so errors are never highlighted.
This PR switches from DTE events to communication between extensions (see eef66fe). When the syntax extension is not installed or an older version is in use, no error is raised and no highlighting is applied. In future, we might want to show a warning but it needs to be nondisruptive (not a message box).
=> Restore error highlighting in source files

VSRAD.Package/BuildTools/Errors/Parser.cs, VSRAD.Package/ProjectSystem/ErrorListManager.cs, VSRAD.PackageTests/BuildTools/Errors/ParserTests.cs
Add to the error list lines that begin with `ERROR` and `WARNING` keywords. Such errors may be present in addition to `clang/script` errors.
=> Errors with keywords

VSRAD.Package/BuildTools/BuildErrorProcessor.cs, VSRAD.Package/BuildTools/Errors/Parser.cs, VSRAD.Package/ProjectSystem/ActionLogger.cs, VSRAD.Package/ProjectSystem/ErrorListManager.cs, VSRAD.Package/Server/ActionRunResult.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/RemoteCommandExecutor.cs, VSRAD.PackageTests/BuildTools/BuildToolsServerTest.cs, VSRAD.PackageTests/BuildTools/Errors/LineMapperTests.cs, VSRAD.PackageTests/BuildTools/Errors/ParserTests.cs, VSRAD.PackageTests/Server/RemoteCommandExecutorTests.cs
* fixed regex to detect errors containing windows filepaths
* now the step outputs are parsed (to detect errors) separately for each step
=> Error parser fixes

VSRAD.Package/Commands/ActionsMenuCommand.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/ActionLogger.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml, VSRAD.Package/Server/ActionRunResult.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.PackageTests/ProjectSystem/ActionLoggerTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs, VSRAD.PackageTests/Server/DebugSessionTests.cs
Added `Continue action execution on errors` checkbox.
If enabled: on any step non-zero exit code user gets warning, however further steps is trying to be executed
If disabled: on any step non-zero exit code user gets error and action execution stops
=> Continue action exec on err

VSRAD.Package/BuildSystem/Rules/RADDebugger.xaml
Addresses #147 
Fixes "No data source in this context" error when using RAD debugger in VisualC projects.
Note that you'll have to copy new version of `RADDebugger.xaml` to the `ImportAfter/` directory to apply the fix
=> fixed no data source in this context error

VSRAD.Package/Options/ProjectOptions.cs
Resolves #154 
Currently, project configuration is saved using `File.WriteAllText`, which does not flush file contents to disk, so a system hang/crash can leave the file in a corrupted state (filled with zero bytes).
To ensure that the configuration file always remains in a valid state, we first create a temporary file (`.conf.json.tmp`), then rename it to `.conf.json` after the data is written to disk.
=> Prevent configuration file corruption

VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/GroupIndexSelector.cs, VSRAD.Package/DebugVisualizer/VisualizerContext.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/Server/BreakState.cs, VSRAD.Package/Server/BreakStateDispatchParameters.cs, VSRAD.Package/Server/DebugSession.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs, VSRAD.PackageTests/Server/BreakStateDispatchParametersTests.cs, VSRAD.PackageTests/Server/DebugSessionTests.cs, VSRAD.PackageTests/VSRAD.PackageTests.csproj
Addresses #140
Addresses #141 
This PR expands the function of `status file`. Status file was used to provide some text that appears in `Debug Visualizer` after every debug run. Now it contains some dispatch parameters following this pattern:
```
grid size (512, 1, 1)
group size (64, 1, 1)
wave size 32
comment status string
```
In the example above following parameters are set:
* `grid size X` = 512, `grid size Y` = 1 and `grid size Z` = 1
* `group size X` = 64, `group size Y` = 1 and `group size Z` = 1
* `wave size` = 32
* `comment` = "status string"
This parameters affecting some project properties:
* `NDRange 3D` is set true if any of `grid size Y` and `grid size Z` is not zero
* `Group Size` is set according to `group size X` (3D group sizes is not supported yet)
* `DimX`, `DimY` and …
=> Status file

VSRAD.Package/Server/CommunicationChannel.cs
Addresses #159 
If current connection is down, the extension will take one attempt to reconnect to server. That way you would not get an error if you rebooted server on remote machine.
=> Server reconnect attempt

VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/ContextMenus/SubgroupContextMenu.cs, VSRAD.Package/DebugVisualizer/GroupIndexSelector.cs, VSRAD.Package/DebugVisualizer/SelectionController.cs, VSRAD.Package/DebugVisualizer/VisualizerContext.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/DebugVisualizer/Wavemap/WavemapImage.cs, VSRAD.Package/DebugVisualizer/Wavemap/WavemapOffsetInput.xaml, VSRAD.Package/DebugVisualizer/Wavemap/WavemapOffsetInput.xaml.cs, VSRAD.Package/DebugVisualizer/Wavemap/WavemapView.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/BuiltinActionFileEditor.xaml, VSRAD.Package/Server/BreakStateData.cs, VSRAD.Package/Utils/MagicNumberConverter.cs, VSRAD.Package/VSRAD.Package.tt, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs, VSRAD.PackageTests/ProjectSystem/Profiles/LegacyProfileImporterTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs, VSRAD.PackageTests/Server/BreakStateTests.cs, VSRAD.Syntax/Package.vsct
* Waves with inactive lanes or non-matching magic number are grayed out in wavemap
* Wave size can be manually set in visualizer
* Visualizer context menu: _Hide This_ is disabled when displaying the menu for the _Name_ column, _Show All Columns_ is always enabled
* All items in the _RAD Debug_ toolbar have labels
* Setting group size to a value that's not divisible by wave size no longer causes a crash
=> Minor visualizer fixes

VSRAD.Package/Commands/ProfileDropdownCommand.cs, VSRAD.Package/Options/ProjectOptions.cs, VSRAD.Package/ProjectSystem/Profiles/RecentlyUsedHostsEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/RecentlyUsedHostsEditor.xaml.cs, VSRAD.Package/Utils/MruCollection.cs, VSRAD.Package/VSRAD.Package.csproj
* Clicking _Edit..._ at the bottom of the target hosts dropdown opens the editor window, where hosts can be added, edited or removed.
* Changes can be discarded by pressing _Cancel_ or closing the editor window and choosing _No_ in the _Save changes?_ dialog.
* The maximum number of hosts in the dropdown is no longer limited.
=> Add target hosts editor

VSRAD.Package/BuildSystem/DeployedBuildSystem/RADProject.targets, VSRAD.Package/Options/ProjectOptions.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileTransferManager.cs, VSRAD.Package/ProjectSystem/Project.cs
Renamed `.conf.json` to `.profiles.json` so old config would not be overwritten.
This PR adds the ability to successfully run the project with old `.conf.json` config. After first updating of configs, the configs will be updated to match the new `.profiles/.user` format, that makes the migration to new configs format seamless for user.
=> Obsolete config format import

VSRAD.Syntax/Core/Tokens/DefinitionToken.cs, VSRAD.Syntax/FunctionList/FunctionListProvider.cs, VSRAD.Syntax/IntelliSense/Helper.cs, VSRAD.Syntax/IntelliSense/IntellisenseController.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs, VSRAD.Syntax/IntelliSense/SignatureHelp/InstructionSignature.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
=> IntelliSense syntax fixes

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/Commands/AddToWatchesCustomSliceEditor.xaml, VSRAD.Package/Commands/AddToWatchesCustomSliceEditor.xaml.cs, VSRAD.Package/Constants.cs, VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/NumberInput.xaml, VSRAD.Package/DebugVisualizer/NumberInput.xaml.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerContext.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/TypedSliceWatchView.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/Options/VisualizerAppearance.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/Utils/ArrayRange.cs, VSRAD.Package/Utils/DataFormatter.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.Package/VSRAD.Package.tt, VSRAD.PackageTests/DebugVisualizer/ColumnStylingTests.cs, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs
* New feature `Append leading zeroes to binary/hex numbers` available in Visualizer Appearance tab inside Options window.
When active, it will make hex numbers presented as 8 digits (`0x00000001`) and binary as 32 digits.
* New feature `Insert separator in binary/hex mode between groups of X digits` available in Visualizer Appearance tab inside Options window. When `X` is not zero, it will insert whitespaces each `X` characters in bin/hex representations starting from last digit (`0x4 23 13`).
* New feature `Insert separator in int/uint mode between groups of X digits` available in Visualizer Appearance tab inside Options window. When `X` is not zero, it will insert whitespaces each `X` characters in int/uint representations starting from last digit (`1 000 000`).
* Custom array slices …
=> Visualizer improvements

VSRAD.Syntax/Core/DocumentAnalysis.cs, VSRAD.Syntax/IntelliSense/Helper.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs, VSRAD.Syntax/Options/GeneralOptionModel.cs, VSRAD.Syntax/Options/GeneralOptionPage.cs, VSRAD.Syntax/Options/GeneralOptionProvider.cs, VSRAD.Syntax/Options/Instructions/InstructionListLoader.cs, VSRAD.Syntax/Package.cs
Exception logs:
<details>
<summary>Log 1</summary>
<description>System.AggregateException: One or more errors occurred. ---&gt; System.Threading.Tasks.TaskCanceledException: Buffer changes have not yet been processed&#x000D;&#x000A;   at VSRAD.Syntax.Core.DocumentAnalysis.&lt;GetAnalysisResultAsync&gt;d__12.MoveNext() in D:\tmp\radeon-asm-debugger\VSRAD.Syntax\Core\DocumentAnalysis.cs:line 38&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at VSRAD.Syntax.IntelliSense.NavigationTokenService.&lt;GetNavigationsAsync&gt;d__4 …
=> Fix unhandled syntax exceptions

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Macros/MacroListEditor.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileTransferManager.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/Utils/VsEditor.cs
Changed:
* Renamed `Break Args` field to `App Args 2`, `RadDebugBreakArgs` macro to `RadDebugAppArgs2`;
* Previously, any `Open in editor` step would change the active document window to newly opened one even if this document is opened in a separate tab. Now the active document will remain the same as it was before running of the action. If `Line Marker` present, the corresponding line will be active in opened file once user change the tab to it.
* Previously, `Add to watches` feature selected active word including indices (`var[a][b][c]`), now it ignores them (in previous example just `var` will be added to the watch list).
Added:
* `App Args 3` field and corresponding macro `RadDebugAppArgs3`.
Fixed:
* NRE if old config file didn't had `TargetHosts` field
=> Ux improvements

VSRAD.DebugServer/Handlers/FetchResultRangeHandler.cs, VSRAD.DebugServer/SharedUtils/TextDebuggerOutputParser.cs, VSRAD.DebugServerTests/Handlers/FetchResultRangeHandlerTest.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/BreakStateData.cs, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs, VSRAD.PackageTests/Server/BreakStateTests.cs
See the commit message for a detailed description of the new approach. The difference in speed is quite noticeable: 230-270 ms with the old code, 22-23 ms with the new version, as tested on an FX-8120 machine with a typical output file (~2MB).
=> Speed up text output parsing by ~10x

VSRAD.Syntax/Core/DocumentTokenizer.cs
As noted in the code, sometimes `ContentChanged` is raised when there are no changes to the buffer snapshot. This usually happens when the file is reloaded from disk but the content is unchanged (e.g. when using Disassemble/Preprocess actions from VSRAD.Package). The snapshot version in this case, however, gets incremented, so when `AnalysisClassifier.GetClassificationSpans` is called later, the early return condition (`analysisResult.Snapshot != span.Snapshot`) triggers, and the highlighting is no longer shown in the editor.
=> Fix syntax highlighting "disappearing" when the file is reloaded

VSRAD.Syntax/IntelliSense/SignatureHelp/Signature.cs
Steps to reproduce:
1. Enable IntelliSense support in _RadeonAsm Options_
1. Define a parameterless function (asm2)
2. Start typing an invocation of this function
3. When the opening brace is reached, `FunctionSignature.Initialize` calls `SetCurrentParameter(0)`, which causes this exception because the parameter list is empty
=> Syntax: fix ArgumentOutOfRangeException in function parameter autocompletion

VSRAD.Syntax/Core/Lexer/Asm2Lexer.cs, VSRAD.SyntaxParser/RadAsm2.g4
This PR adds `assigned`, `label` and `print` keywords to the asm2 syntax.
They are highlighted in the text with a default color for keywords.
=> Expand asm2 syntax keywords

VSRAD.Syntax/SyntaxHighlighter/Classifier.cs
This PR fixes syntax highlighting due to wrong token search boundaries. Especially this problem appeared if the token goes before the `if-elsif-endif` block such as:
```
.macro someMacro
.if someIf
.endif
.endm
```
=> Fix syntax highlighting

VSRAD.Syntax/IntelliSense/Completion/CompletionSource.cs, VSRAD.Syntax/IntelliSense/Completion/TokenizerExtension.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
This PR fixes autocomplete trigger behavior. Now autocomplete will not trigger with **function** and **variable** declaration such as:
```
.macro someMacro
^ 
not triggered at this position
.endm
.set someVariable
^
not triggered at this position
```
=> Fix intellisense autocomplete

VSRAD.Package/Utils/VsEditor.cs
This PR changes Open in Editor step so the focus will always be on opened file (as it was before #201).
=> Open in Editor preserving active document rollback

VSRAD.Syntax/Core/Parser/Asm2Parser.cs, VSRAD.Syntax/IntelliSense/Completion/TokenizerExtension.cs
This PR provides parsing of label declarations using the `label` keyword. Such symbols have the same behavior as variables.
=> Label declaration

VSRAD.DebugServer/Client.cs, VSRAD.DebugServer/IPC/StreamExtensions.cs, VSRAD.Package/Server/CommunicationChannel.cs
Properly handle this situation by:
1) throwing an exception (EndOfStream) instead of silently returning null;
2) always force disconnecting when there's an exception.
The problem only affected the VS extension; Debug Server's behavior was correct. The changes in `Client.cs` are only needed to switch from checking for `null` to catching the end of stream exception.
=> Fix NRE when debug server response cannot be read

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml
Added new `Match brackets on Add To Watches` property in Options window, that specifies whether brackets (`[]`) and their contents should be ignored on `Add to Watches` operation.
=> Add to Watches optional brackets matching

VSRAD.Syntax/Core/Lexer/Asm2Lexer.cs, VSRAD.Syntax/Core/Parser/Asm2Parser.cs, VSRAD.SyntaxParser/RadAsm2.g4
This PR fixes preprocessor keyword highlighting.
Lexer result:
```
#i
^ CHARP
^ IDENTIFIER
```
After the preprocessor keyword is fully written (`#if`), tokenizer will apply changes (changed text: `if`) only to the _IDENTIFIER_ token, because text changes intersect only with this token, but not with CSHARP. 
After that, lexer result for the changed text will be:
```
#if
^ CHARP
^ IF keyword
```
The solution is to remove `SHARP` (**#** symbol) token, but add `CLOSURE_IDENTIFIER` token. 
In this case lexer result will be:
```
#i
^ CLOSURE_IDENTIFIER
``` 
And after adding the letter `f`, tokenizer will apply the changes to the `CLOSURE_IDENTIFIER` token. And lexer result will be:
```
#if
^ PP_IF keyword
```
=> Fix tokenization of preprocessor keyword

VSRAD.Syntax/IntelliSense/Peek/PeekableItemSource.cs
This pull request provides automatic opening of the navigation list at _Peek Definition_ action, if the number of navigation token is more than 1.
Some instructions have more than one declarations (`v_cndmask_b32`).
Now if you use Peak Definition on the `v_cndmask_b32` instruction, a navigation list with all declarations will be opened
=> Open navigation list on peek definition

VSRAD.Syntax/IntelliSense/Completion/Providers/InstructionCompletionProvider.cs
This pull request fixes multiple instances of instructions in the autocompletion list.
For example, if all instruction sets are selected (`instruction set selector -> All`).
Then completion list contained multiple **identical instructions** from different _Instruction Sets_.
This pull request fixes this issue:
=> Combine instruction completions

VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs, VSRAD.Syntax/FunctionList/Helper.cs, VSRAD.Syntax/Options/BaseOptionModel.cs, VSRAD.Syntax/Options/BaseOptionPage.cs, VSRAD.Syntax/Options/GeneralOptionPage.cs, VSRAD.Syntax/Options/GeneralOptionProvider.cs, VSRAD.Syntax/Options/GeneralOptions.cs, VSRAD.Syntax/Package.cs, VSRAD.Syntax/VSRAD.Syntax.csproj
This PR doesn't fix anything, but it cleans up the options module.
The options have been split into two components:
- Option Page
- Option Model
The first is responsible for presenting options on the dialog page.
The second is responsible for saving and loading options from the Visual Studio registry.
This makes the options more expandable.
This PR may also slightly speed up the extension loading.
=> Options refactoring

VSRAD.Syntax/Helpers/CustomThreadHelper.cs, VSRAD.Syntax/Options/GeneralOptionProvider.cs, VSRAD.Syntax/Options/GeneralOptions.cs, VSRAD.Syntax/Options/Instructions/InstructionListManager.cs
Before reviewing this pull request, #243 must be merged into dev-stable.
This PR provides automatic saving of the selected instruction set. 
The next time the Visual Studio is launched, the instruction set that was selected in the previous session will be automatically selected. 
The selected instruction set is different for `asm1` and `asm2`.
=> Save selected instruction set

VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/ProjectSystem/ActionLauncher.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml, VSRAD.Package/Utils/VsEditor.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs
This PR modifies the behavior of Open in Editor step.
Added two new settings to the Options Window:
* **Open in Editor: Force new document to be opened in the opposite tab**: if checked, new document will always be opened in the separate vertical tab group from current active document, in existing, if possible, or in new, if there is only one tab.
* **Open in Editor: Preserve active document**: if checked, Open in Editor step would not change the active document. Otherwise, opened document will become active.
=> Open in Editor: Tab groups handling [dev-stable]

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/Utils/ArrayRange.cs, VSRAD.PackageTests/Utils/ArrayRangeTests.cs
This PR modifies behavior of `Add to watches as array` feature with `Match brackets` turned off when manually selecting text that contain brackets.
Assume the selected text is `v_buf[i]` and user selected array from 0 to 1:
- With match brackets turned on `v_buf[i+0]` and `v_buf[i+1]` will be added to watch list;
- With match brackets turned off `v_buf[i][0]` and `v_buf[i][1]` will be added to watch list.
=> Add to watches as array brackets matching

VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/VSRAD.Package.tt
This PR changes default values for watch type and shortcut for `Add to watches` command.
* `Add to watches`: `Alt+A` -> `Ctrl+E,A`
* Default watch type changed from `HEX` to `INT`
=> Default settings tweaks

VSRAD.Package/Commands/AddToWatchesCommand.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Utils/ArrayRange.cs, VSRAD.Package/Utils/BreakModeConverter.cs
This PR provides a few fixes that related to the last changes in the Debugger plugin.
* Added support for optional brackets matching when using custom slices for watch adding.
* Fixed break mode descriptions for better matching with short versions.
* Fixed default values setting for `ForceOppositeTab` and `PreserveActiveDoc` properties.
=> Debugger plugin fixes

VSRAD.Package/Utils/VsEditor.cs
This PR provides small fix for the Open in Editor feature.
Steps to reproduce:
1. Check both `Open in editor: ...` options.
2. Create 2 separate tab groups, set focus to the first one.
3. Run action with `Open in editor` step (the file should not be opened in any tab before this).
As a result, the file will be opened in the second tab, but it will be hidden because active document from this tab will remain same.
=> Move document to opposite tab fix

VSRAD.Syntax/Core/DocumentTokenizer.cs
This PR fixes syntax highlighting "disappearing" when the file is reloaded. 
Original PR which is already in `dev` branch: #207 
This usually happens when the file is reloaded from disk but the content is unchanged (e.g. when using Disassemble/Preprocess actions from VSRAD.Package). In this case, the analysis result was not updated, which led to the disappearance of the syntax highlighting.
=> Fix stale analysis result on document relaod

VSRAD.Syntax/SyntaxHighlighter/Classifier.cs
This PR fixes function argument highlighting.
In this example `arg1` and `arg2` function parameters were not highlighted. 
```
.macro some_macro arg1, arg2
.set value, \arg1
.endm
```
=> Fix function argument highlighting

VSRAD.Syntax/Core/Document.cs
[FileActionTypes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.fileactiontypes?view=visualstudiosdk-2019) is flag enum. It's incorrect to compare `e.FileActionType` with `FileActionTypes.DocumentRenamed` because it may have a different value. 
For example, on `save as` the value is `FileActionTypes.DocumentRenamed | FileActionTypes.ContentSavedToDisk` so renaming will not be handled.
=> Handle document renaming correctly

VSRAD.Package/ProjectSystem/BreakpointTracker.cs
This PR fixes the behavior of the breakpoint placing in the `Rerun Line` mode. Previously, the same line would be selected for `Continue` even if user deletes original breakpoint, now the next line (or last line in doc, if there is no more breakpoints) will be selected.
=> Rerun line behavior fix

VSRAD.Package/Options/Actions.cs, VSRAD.Package/ProjectSystem/Profiles/ActionEditor.xaml, VSRAD.Package/ProjectSystem/Profiles/ProfileTransferManager.cs, VSRAD.PackageTests/ProjectSystem/Profiles/Fixtures/ConfigsTest.vcxproj.conf.json, VSRAD.PackageTests/ProjectSystem/Profiles/ObsoleteFormatProfileImportTests.cs
This PR:
* Adds compatibility between #259 and #254 : now the `IfNotModified` property is correctly handled during the obsolete config import.
* Makes `Do Not Copy` default option for `IfNotModified` property.
* Updates tests from #254 to match #259 configs format.
=> CopyFile step fixes

VSRAD.Syntax/Core/Lexer/Asm2Lexer.cs, VSRAD.SyntaxParser/RadAsm2.g4
This PR adds new lexer tokens for `asm2` syntax.
Added escape `\` token to fix identifier parsing which is joined with `\`.
Previously, **_arg1_** and **_arg2_** were not tokenized as identifiers (**_arg1\\_** and **_arg2\\_** were _UNKNOWN_ tokens). Because of what the parser did not work correctly in such a situation.  Now **_arg1\\_** is tokenized as 2 different tokens - _IDENTIFIER_, _ESCAPE_.
```
function (arg1\
,arg2\
,arg3)
end
```
Added new native functions: `float, floor, map, zip, head, tail, take, drop, rotate, replicate, reverse, cons, concat, list, s_list, v_list`
Added right arrow `->` operator used by lambdas.
=> Asm2 lexer update

VSRAD.Syntax/Helpers/SnapshotPointExtension.cs
Fixed identifier highlighting for such case (`value1`):
```
var value1 = 1
var value2 = 2
some_func(value1\
,value2)
```
=> Fix highlighting identifier concatinated with escape token

VSRAD.Package/DebugVisualizer/VisualizerHeaderControl.xaml, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/VisualizerOptions.cs, VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Macros/MacroListEditor.xaml.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileTransferManager.cs
#201 but targeted on `dev-stable`. Diff:
* No changes connected to `Open in editor` since this feature is done by #246.
* No fix NRE if old config file didn't had TargetHosts field, done by #254
Original description with respect to diff:
Changed:
* Renamed `Break Args` field to `App Args 2`, `RadDebugBreakArgs` macro to `RadDebugAppArgs2`;
* Previously, `Add to watches` feature selected active word including indices (`var[a][b][c]`), now it ignores them (in previous example just `var` will be added to the watch list).
Added:
* `App Args 3` field and corresponding macro `RadDebugAppArgs3`.
=> Ux improvements [stable]

VSRAD.Package/ProjectSystem/EditorExtensions/BreakLineGlyphTagger.cs
Resolves #228 
Steps to reproduce:
1. Insert breakpoint in `BreakGlyphTagger.cs:100`
2. Enable `Memory Usage` in the `Diagnostic Tools`.
3. Open project in the debug instance of VS.
4. Open first document, take the memory snapshot.
5. Open/Close document `N`-times.
6. Take the second memory snapshot.
7. Open diff between snapshots, filter objects by `VSRAD.Package` predicate.
8. Sort by `Count Diff.` column.
9. See the `+N` of `BreakGlyphTagger` objects (screenshot below).
Visual Studio seems to be cashing some of Tagger objects. However, this PR reduces number of Tagger instances from one per any opened document in the session to several instances, which have the roots inside the VS internal structures, according to memory profiler. So, I consider the possible memory leak as fixed.
=> BreakLineGlyphTagger memory leak fix

VSRAD.PackageTests/DebugVisualizer/GroupIndexSelectorTests.cs
This PR fixes `DimensionClippingTest`.
The 156f497133db0831c4431be86f13593b42f87f4a commit slightly changed the dimension clipping logic, this PR updates corresponding test.
=> DimensionClippingTest fix

VSRAD.Package/ProjectSystem/ActionLogger.cs, VSRAD.Package/ProjectSystem/OutputWindow.cs
This PR modifies the behavior of the `RAD Output` pane. Now it is cleared before every action execution, which means that it stores only info about last action run.
=> Clear RAD Output on every action run

VSRAD.Package/DebugVisualizer/MouseMove/ScaleOperation.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerTable.cs, VSRAD.Package/DebugVisualizer/TableState.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/Options/VisualizerAppearance.cs, VSRAD.Package/ToolWindows/OptionsControl.xaml
This PR modifies the behavior of `Name` column of `Debug Visualizer`. Insted of auto-setting the width based on contents, now user can scale this column manually.
=> Debug Visualizer Name column scaling

VSRAD.Package/ProjectSystem/Project.cs, VSRAD.Package/ProjectSystem/SolutionManager.cs
This PR fixes critical bug, when project configs becoming unusable after changing of the startup project. Steps to reproduce:
1. Open solution with multiple projects
2. Open `Debug Visualizer` and run debug
3. Change startup project
4. Change startup project back to initial project
5. Add new watch
6. Run debug again
You should see that the new watch is grayed out and it's data is not displayed.
=> Set as Startup Project behavior fix

VSRAD.Package/ProjectSystem/ActiveCodeEditor.cs
Resolves #281.
For escape token usage refer to #279.
Before this PR when using `Add to wathches` on the `arg1` in the following example,
the `arg1\` watch would be added. This PR excludes the `\` escape token from `Add to watches`
match.
```
function (arg1\
,arg2\
,arg3)
end
```
=> Add to Watches: Added escape token handling

VSRAD.DebugServer/Client.cs, VSRAD.DebugServer/IPC/StreamExtensions.cs, VSRAD.Package/Server/CommunicationChannel.cs
#211 but targeted on `dev-stable`.
Original description by @timlathy:
Properly handle this situation by:
1. throwing an exception (EndOfStream) instead of silently returning null;
2. always force disconnecting when there's an exception.
The problem only affected the VS extension; Debug Server's behavior was correct. The changes in `Client.cs` are only needed to switch from checking for `null` to catching the end of stream exception.
=> Fix NRE when debug server response cannot be read [stable]

VSRAD.Package/DebugVisualizer/ContextMenus/TypeContextMenu.cs, VSRAD.Package/DebugVisualizer/CustomTableGraphics.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerContext.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/TypedSliceWatchView.cs, VSRAD.Package/DebugVisualizer/VariableType.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/DebugVisualizer/Watch.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Utils/DataFormatter.cs
This PR adds more flexible way to define datatypes. Now you can not only choose representation (`Hex`, `Int`, `UInt`, `Float`, `Bin` or `Half`), but also size - 32, 16 or 8 bits (only 32 and 16 for `Float`).
_Note_: For now `SliceVisualizer` is not supported, since it's last version is not on stable branch and we still discuss the details of it's implementation.
=> Flexible datatypes

VSRAD.Package/Commands/ActionsMenuCommand.cs, VSRAD.Package/ProjectSystem/ActionLauncher.cs, VSRAD.Package/ProjectSystem/DebuggerIntegration.cs, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindow.xaml, VSRAD.Package/ProjectSystem/Profiles/ProfileOptionsWindowContext.cs, VSRAD.Package/Utils/ActionHelper.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs, VSRAD.PackageTests/ProjectSystem/Profiles/ProfileOptionsWindowContextTests.cs
*#265 but targeted on current `dev-stable`*
___
Resolves #263 
This PR improves validation of the Action names. Previously, it was possible to have two Actions with the same name, which in some cases (for example `RunAction`) could lead to the undefined behaviour and even to crash of the Visual Studio.
This PR fixes possible crashed and adds new features:
* Now new Actions added by a `+` button are provided with unique number suffix to prevent creating of two Actions with the same name:
* Added additional validation for renaming an Action, which ensures that new Action name is unique:
=> Action Names handling [stable]

VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/Options/ProjectOptions.cs
This PR fixes some default options values.
For example, after creation of new project on `dev-stable`, `TargetHosts` control will look like this:
This PR returns proper behavior:
* Looks like I added the only reference for `DefaultOptionValues` with this change. Do we need it? And if we do, maybe consider using it instead of hardcode values?
* We need to check initialization of others options, probably there is some issues similar to `TargetHosts`.
=> [wip] Default Options Values

VSRAD.Package/ProjectSystem/Macros/DirtyProfileMacroEditor.cs
Resolves #297 
When no file opened in editor, VS hanged on attempt to add a new step in Profile Editor. This was caused by the incorrect error handling in `DirtyProfileMacroEditor`, which this PR fixes.
=> Profile Editor Hang Fix

VSRAD.Syntax/Core/DocumentFactory.cs, VSRAD.Syntax/Core/IDocumentFactory.cs, VSRAD.Syntax/FunctionList/FunctionListProvider.cs
This PR fixes incorrect handling of opening new file in editor by the `Function List`.
Steps to reproduce:
1.  Open any assembly source file in project, so `Function List` will update according to it's contents
2. Check both `Open in Editor: ...` checkboxes inside `RAD Options`
3. Create action that contains `Open in Editor` step with other assembly source file, that should trigger `Function List` to update
4. Run this action
You will see, that new pane is created for the source file from the `Open in Editor` step while active document tab should remain the same. However, `Function List` will be updated with contents of newly opened file, so it will be desynchonized with current active document, which is not expected.
With changes in this PR `Function List` won't update if newly opened …
=> Fix: Function List proper Open in Editor handling

VSRAD.Package/BuildTools/Errors/Parser.cs, VSRAD.PackageTests/BuildTools/Errors/ParserTests.cs
Resolves #311 
This PR adds support for Clang `Fatal errors` that used to be ignored.
Example of error message:
```
input.s:16:10: fatal error: 'abcde.s' file not found
#include "abcde.s"
^~~~~~~~~
```
=> Clang messages not appear in Error List fix

VSRAD.Build/VSRAD.Build.csproj, VSRAD.Syntax/FunctionList/FunctionListControl.xaml, VSRAD.Syntax/FunctionList/FunctionListControl.xaml.cs
Fixes [#303 ](https://github.com/vsrad/radeon-asm-tools/issues/303).
Column sizes are explicitly calculated on the rendering stage.
=> Incomplete function names fix

VSRAD.Package/DebugVisualizer/GroupIndexSelector.cs
This PR fixes GroupSize value for NDRange3D mode.
Previously, dispatch parameters in visualizer did not work properly for 3D groups.
Dispatch parameter example:
```
grid_size (32, 1, 8)
group_size (32, 1, 8)
wave_size 32
```
=> [BugFix] GroupSize value for NDRange3D mode

VSRAD.Package/DebugVisualizer/MouseMove/ScaleOperation.cs
This PR fixes `ResizeHalf` scaling mode when phantom column is visible (when data columns do not occupy the whole table)
The difference is most visible on following gif's:
=> Fixed ResizeHalf scaling with phantom column

README.md, VSRAD.Package/Properties/AssemblyInfo.cs, VSRAD.Package/Server/CommunicationChannel.cs
As for now, installed release version of VSRAD.Package will crash Visual Studio or extension will fail to initialize.
This is due to incorrect version checking of extension, introduced in #333. In this case, Debug and Release configuration actually behave differently. As introduced in [article](https://www.visualstudioextensibility.com/2016/07/11/the-four-versions-of-a-visual-studio-package/), we actually need to set the extension versions in _two_ locations:
1. `VSRAD.Package\source.extension.vsixmanifest`
2. `VSRAD.Package\Properties\AssemblyInfo.cs`
This PR introduces changes needed to fix current master branch Release behavior.
=> Proper extension version checking in Release configuration

VSRAD.Package/DebugVisualizer/ContextMenus/TypeContextMenu.cs, VSRAD.Package/DebugVisualizer/CustomTableGraphics.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerContext.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerHeaderControl.xaml, VSRAD.Package/DebugVisualizer/SliceVisualizer/TypedSliceWatchView.cs, VSRAD.Package/DebugVisualizer/VariableType.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/DebugVisualizer/Watch.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Utils/DataFormatter.cs, VSRAD.PackageTests/DebugVisualizer/DataFormattingTests.cs, VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs, VSRAD.PackageTests/ProjectSystem/Profiles/ObsoleteFormatProfileImportTests.cs, VSRAD.PackageTests/VSRAD.PackageTests.csproj
This PR adds new Int/UInt packed representations for Debug visualizer. One 32-bit value, two 16-bit values or four 8 bit values are supported.
Notes:
* this PR strongly relies on https://github.com/vsrad/radeon-asm-tools/pull/289 with some extra functionality commented out, but not removed in case we would want to bring packed representations for types other than Int/UInt
* large chunks of code that deal with computing the relative values for Slice Visualizers heatmap view were commented out either, since it need to be refactored to work with packed representation and we do not have Slice Visualizer in current upstream and the details of it's realization are still under development
=> Packed Int/UInt types

VSRAD.Syntax/IntelliSense/Completion/Providers/CompletionItem.cs, VSRAD.Syntax/IntelliSense/IntellisenseTokenDescription.cs
This PR adds a description (text specified in the comment next to the token) for the token with multiple definitions such as instructions. Users don't need to click on instructions in a quick-info tooltip anymore to get a description of the instruction.
Example:
How it worked before:
=> Add a description for token with multiple definitions

VSRAD.Syntax/IntelliSense/Navigation/NavigationTokenService.cs
Previously, the quick info tooltip and the navigation didn't work with instructions in a closure like this:
```
#v_add_co_u32(v1, vcc, v2 ,v3)
```
⚠️**Low-risk change**
=> Fix syntax intellisense for instructions in a closure

VSRAD.Deborgar/IEngineIntegration.cs, VSRAD.DeborgarTests/ProgramTests.cs, VSRAD.Package/Errors.cs, VSRAD.Package/Options/Actions.cs, VSRAD.Package/ProjectSystem/ActionLauncher.cs, VSRAD.Package/ProjectSystem/BreakpointTracker.cs, VSRAD.Package/ProjectSystem/DebuggerIntegration.cs, VSRAD.Package/ProjectSystem/EditorExtensions/BreakLineGlyphTagger.cs, VSRAD.Package/ProjectSystem/Macros/DirtyProfileMacroEditor.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs, VSRAD.PackageTests/Server/ActionMacroEvaluationTests.cs
* "Rerun single line" breakpoint mode now moves to the next breakpoint if the current one is removed.
* If no breakpoints are set, and we launch an action that uses `$(RadBreakLine)`, an error message is now shown. If the action does not use `$(RadBreakLine)` (e.g. "Disassemble"), no error message is shown.
The large diff is mostly due to the fact that predefined macros like `$(RadBreakLine)` were assumed to be always available, and if the real value was missing (say, if there are no breakpoints), a hardcoded default was picked instead. Such design is undesirable as it results in seemingly random behavior that hides the real problem, so the code had to be refactored to allow for errors during evaluation of predefined macros.
=> Breakpoint tracking fixes

VSRAD.Package/DebugVisualizer/CellStyling.cs, VSRAD.Package/DebugVisualizer/ComputedColumnStyling.cs, VSRAD.Package/DebugVisualizer/CustomTableGraphics.cs, VSRAD.Package/DebugVisualizer/RowStyling.cs, VSRAD.Package/DebugVisualizer/SliceVisualizer/SliceVisualizerContext.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/DebugVisualizer/Watch.cs, VSRAD.Package/Options/Actions.cs, VSRAD.Package/Options/DebuggerOptions.cs, VSRAD.Package/Options/DefaultOptionValues.cs, VSRAD.Package/ProjectSystem/Macros/MacroEvaluator.cs, VSRAD.Package/ProjectSystem/Macros/MacroListEditor.xaml.cs, VSRAD.Package/Server/ActionRunResult.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Server/BreakState.cs, VSRAD.Package/Server/BreakStateData.cs, VSRAD.PackageTests/DebugVisualizer/ColumnStylingTests.cs, VSRAD.PackageTests/DebugVisualizer/ComputedColumnStylingTests.cs, VSRAD.PackageTests/ProjectSystem/ActionLoggerTests.cs, VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs, VSRAD.PackageTests/ProjectSystem/Macros/MacroEvaluatorTests.cs, VSRAD.PackageTests/Server/ActionRunnerTests.cs, VSRAD.PackageTests/Server/BreakStateTests.cs, VSRAD.ProjectTemplate/RADProject.radproj.user.json
* Breakpoints can have multiple instances, valid watches are different between instances
* Different waves can break at different instances, so each wave now has its own set of watches
* Waves are allocated the same number of dwords (equal to the maximum number of watches per instance). The same watch may have different offsets in different instances
* Watch and break line separator in macros is changed from a colon to a semicolon
* Nested ReadDebugData steps in actions now work properly
=> Support breakpoints with multiple instances

VSRAD.Package/DebugVisualizer/CellStyling.cs, VSRAD.Package/DebugVisualizer/VariableType.cs, VSRAD.Package/DebugVisualizer/VisualizerControl.xaml.cs, VSRAD.Package/DebugVisualizer/VisualizerTable.cs
* Commit watch edits whenever the cell loses focus (previously Enter was required to be pressed, otherwise the edits were discarded)
* Fix the behavior of divider rows, which got broken by #358
=> Minor watch editor fixes

VSRAD.Package/BuildTools/Errors/Parser.cs, VSRAD.PackageTests/BuildTools/Errors/ParserTests.cs
The time taken to scan stdout/stderr for error patterns grew superlinearly with the length of each line. This problem is specific to the Clang error regex, other patterns are easier to detect as they start with special markers.
=> Reduce overhead of error message parsing

VSRAD.Package/DebugVisualizer/VisualizerControl.xaml, VSRAD.Package/DebugVisualizer/VisualizerTable.cs, VSRAD.Package/ToolWindows/BaseToolWindow.cs, VSRAD.Package/Utils/CollectionExtensions.cs, VSRAD.Package/VSPackage.cs
* Replace "Promote to Watches" with more general "Add to Watches"
* Fix confusing Visualizer table focus behavior
* Fix "Insert Row Before", "Insert Row After" breaking list watches
* Make sure that Visualizer window reopens after VS is restarted
* Collapse types context menu to single level, show check marks next to selected options
=> Another round of minor visualizer fixes

VSRAD.DebugServer/ObservableProcess.cs, VSRAD.Package/Commands/ActionsMenuCommand.cs, VSRAD.Package/Options/ProfileOptions.cs, VSRAD.Package/ProjectSystem/ActionController.cs, VSRAD.Package/ProjectSystem/ActionLogger.cs, VSRAD.Package/ProjectSystem/DebuggerIntegration.cs, VSRAD.Package/Server/ActionRunner.cs, VSRAD.Package/Utils/VsInfoBar.cs, VSRAD.Package/VSRAD.Package.csproj, VSRAD.PackageTests/ProjectSystem/DebuggerIntegrationTests.cs
Partially reapplying #194 to the current master, with minor changes to process termination code to speed it up and avoid blocking the UI thread. Remote action cancellation is not included in this PR, but should not be hard to add (just need to pass the cancellation token to `CommunicationChannel` and handle it there).
=> Support action cancellation when running locally
